---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: crawler-ui
  spec:
    rules:
    - http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: crawler-ui
              port:
                number: 8000
