---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: crawler
    component: mongodb
    release: {{ .Release.Name }}
spec:
  type:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
#    name: mongodb
  selector:
    app: crawler
    component: mongodb
    release: {{ .Release.Name }}
