crawler-ui:
  image:
    repository: privalovip/crawler-ui
    tag: latest
  service:
    externalPort: 8000

crawler-bot:
  image:
    repository: privalovip/crawler-bot
    tag: latest
  service:
    externalPort: 8000
