---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqint
  labels:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 15672
  selector:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
