---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: crawler
    component: crawler-ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawler
      component: crawler-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-ui
      labels:
        app: crawler
        component: crawler-ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler-ui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler-ui
          protocol: TCP
        env:
        - name: MONGO_HOST
          value: {{  .Values.db_host | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.db_port | default "27017" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
