---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "crawler-ui.fullname" . }}
#  annotations:
#    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ template "crawler-ui.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
