version: '3.3'

services:

  mongodb:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - mongodb:/data/db
    networks:
      - services_network

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - services_network

  crawler-bot:
    build: ./crawler
    image: ${USERNAME}/crawler-bot:${CRAWLER_BOT_VERSION}
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - services_network

  crawler-ui:
    build: ./ui
    image: ${USERNAME}/crawler-ui:${CRAWLER_UI_VERSION}
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - services_network

volumes:
  mongodb:

networks:
  services_network:
