---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler-bot.fullname" . }}
  labels:
    app: crawler
    component: crawler-bot
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler-bot
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-bot
      labels:
        app: crawler
        component: crawler-bot
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler-bot
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler-bot
          protocol: TCP
        env:
        - name: MONGO_HOST
          value: {{  .Values.dbhost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.dbport | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{  .Values.rmq_host | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{  .Values.rmq_queue | default "rabbitmq" | quote }}
        - name: RMQ_USERNAME
          value: {{  .Values.rmq_username | default "rabbitmq" | quote }}
        - name: RMQ_PASSWORD
          value: {{  .Values.rmq_password | default "rabbitmq" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
