---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler-bot.fullname" . }}
  labels:
    app: crawler
    component: crawler-bot
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler-bot
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-bot
      labels:
        app: crawler
        component: crawler-bot
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler-bot
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler-bot
          protocol: TCP
        env:
        - name: MONGO
          value: mongodb
        - name: RMQ_HOST
          value: rabbitmq
        - name: RMQ_QUEUE
          value: rabbitmq
        - name: RMQ_USERNAME
          value: rabbitmq
        - name: RMQ_PASSWORD
          value: rabbitmq
        - name: CHECK_INTERVAL
          value: "60"
        - name: EXCLUDE_URLS
          value: .*github.com
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
